backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: jilliangmeehan/oatmilky
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Letters"
    name: "letter"
    folder: "src/posts"
    create: true
    identifier_field: number
    description: description
    editor:
      preview: false
    fields:
      - label: "📋 Info"
        name: "info"
        widget: object
        fields:
          - { label: "💌 Letter number", name: "number", widget: "number" }
          - { label: "🖋 Description", name: "description", widget: "string" }
          - { label: "🗓 Publish Date", name: "date", widget: "datetime" }
          - { label: "🖼 Tweet", name: "tweet", widget: "image", allow_multiple: false, choose_url: false }
          - { label: "🔗 Link to tweet", name: "tweet-url", widget: "string" }
      - label: "📝 Letter"
        name: "body"
        widget: object
        fields:
          - label: "💭 On..."
            name: "on"
            widget: object
            fields:
              - { label: "💬 Topic", name: "topic", widget: "string" }
              - { label: "🍵 Jillian's thoughts", name: "jillian-topic", widget: "markdown" }
              - { label: "😴 Summer's thoughts", name: "summer-topic", widget: "markdown" }
          - label: "😴 Summer's picks"
            name: "summer"
            widget: object
            fields:
              - { label: "01 - Summer's pick", name: "summer-title01", widget: "string" }
              - { label: "01 - Description", name: "summer-desc01", widget: "markdown" }
              - label: "01 - Tag"
                widget: select
                name: "summer-tag01"
                create: true
                options: ["📽️ Movie", "📖 Read", "🧠 Wellness", "📺 TV", "🔗 Link", "🎙️ Podcast", "🎮 Game", "🍽️ Food", "💡 Idea", "📱 Tech", "🎶 Music", "💌 Newsletter", "🎉 Event", "🚨 Emergency"]
              - { label: "02 - Summer's pick", name: "summer-title02", widget: "string" }
              - { label: "02 - Description", name: "summer-desc02", widget: "markdown" }
              - label: "02 - Tag"
                widget: select
                name: "summer-tag02"
                create: true
                options: ["📽️ Movie", "📖 Read", "🧠 Wellness", "📺 TV", "🔗 Link", "🎙️ Podcast", "🎮 Game", "🍽️ Food", "💡 Idea", "📱 Tech", "🎶 Music", "💌 Newsletter", "🎉 Event", "🚨 Emergency"]
          - label: "🍵 Jillian's picks"
            name: "jillian"
            widget: object
            fields:
              - { label: "01 - Jillian's pick", name: "jillian-title01", widget: "string" }
              - { label: "01 - Description", name: "jillian-desc01", widget: "markdown" }
              - label: "01 - Tag"
                widget: select
                name: "jillian-tag01"
                create: true
                options: ["📽️ Movie", "📖 Read", "🧠 Wellness", "📺 TV", "🔗 Link", "🎙️ Podcast", "🎮 Game", "🍽️ Food", "💡 Idea", "📱 Tech", "🎶 Music", "💌 Newsletter", "🎉 Event", "🚨 Emergency"]
              - { label: "02 - Jillian's pick", name: "jillian-title02", widget: "string" }
              - { label: "02 - Description", name: "jillian-desc02", widget: "markdown" }
              - label: "02 - Tag"
                widget: select
                name: "jillian-tag02"
                create: true
                options: ["📽️ Movie", "📖 Read", "🧠 Wellness", "📺 TV", "🔗 Link", "🎙️ Podcast", "🎮 Game", "🍽️ Food", "💡 Idea", "📱 Tech", "🎶 Music", "💌 Newsletter", "🎉 Event", "🚨 Emergency"]
  - label: "Other stuff"
    name: "other stuff"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
commit_messages:
    create: 🌱 create {{collection}} “{{slug}}”
    update: 🖍 update {{collection}} “{{slug}}”
    delete: 🗑 delete {{collection}} “{{slug}}”